name: hcs-env
channels:
  - conda-forge
  - conda-forge/label/broken
  - defaults
dependencies:
  - ipython
  - pip
  - scipy
  - pandas
  - numpy
  - requests 
  - matplotlib
  - seaborn
  - jupyter_contrib_nbextensions
  - ipywidgets
  - gdal
    - -r file:requirements.txt
